CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text NOT NULL UNIQUE, password_hash text NOT NULL, refresh_token_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'disconnected', method text, phone_number text, qr_code text, qr_expires_at timestamptz, pairing_code text, min_interval_ms integer NOT NULL DEFAULT 3000, jitter_ms integer NOT NULL DEFAULT 2000, max_messages_per_minute integer NOT NULL DEFAULT 20, failure_threshold integer NOT NULL DEFAULT 5, pause_duration_ms integer NOT NULL DEFAULT 300000, failure_count integer NOT NULL DEFAULT 0, failure_window_started_at timestamptz, throttled_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key_hash text NOT NULL UNIQUE, key_prefix text NOT NULL, name text NOT NULL, allowed_ips text[], rate_limit integer, session_id text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id text, session_id text NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT, "to" text NOT NULL, type text NOT NULL, content text, url text, filename text, mime_type text, template_id uuid REFERENCES templates(id), variables jsonb, reference_id text, source_type text, source_id text, idempotency_key_hash varchar(64), idempotency_scope varchar(128), idempotency_fingerprint varchar(64), status text NOT NULL DEFAULT 'queued', error text, wa_message_id text, queued_at timestamptz NOT NULL DEFAULT now(), sent_at timestamptz, delivered_at timestamptz, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX messages_idempotency_unique ON messages(idempotency_scope, idempotency_key_hash) WHERE idempotency_scope IS NOT NULL AND idempotency_key_hash IS NOT NULL;
CREATE INDEX messages_session_status_idx ON messages(session_id, status);
CREATE TABLE webhooks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), url text NOT NULL, events text[] NOT NULL, secret_encrypted text, session_ids text[], api_key_id uuid REFERENCES api_keys(id) ON DELETE SET NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_deliveries (id uuid PRIMARY KEY, webhook_id uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE, event_id uuid NOT NULL, event text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'queued', attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 3, response_status integer, error text, queued_at timestamptz NOT NULL DEFAULT now(), delivered_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE queue_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), queue_name text NOT NULL, job_id text NOT NULL UNIQUE, name text NOT NULL, data jsonb NOT NULL, status text NOT NULL DEFAULT 'waiting', priority integer NOT NULL DEFAULT 0, attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 3, error text, processed_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), action text NOT NULL, entity_type text, entity_id text, user_id uuid REFERENCES users(id) ON DELETE SET NULL, metadata jsonb, ip_address inet, created_at timestamptz NOT NULL DEFAULT now());
